# [START runtime]
runtime: custom
env: flex
entrypoint: gunicorn --timeout 60 --workers 4 --bind :$PORT "ppl_eraser_api:create_app('production')"

resources:
  cpu: 4
  memory_gb: 10

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 50
  timeout_sec: 45
  failure_threshold: 3
  success_threshold: 2
  app_start_timeout_sec: 300

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
# [END runtime]
